# SonarQube - MenUnderFire Frontend
sonar.projectKey=MenUnderFire-frontend
sonar.projectName=Men Under Fire - Frontend
sonar.projectVersion=1.0

sonar.host.url=http://172.16.255.10:9002

sonar.sources=src
sonar.tests=src

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/*.test.ts,\
  **/*.test.tsx,\
  **/*.spec.ts,\
  **/*.spec.tsx

sonar.test.inclusions=\
  **/*.test.ts,\
  **/*.test.tsx,\
  **/*.spec.ts,\
  **/*.spec.tsx

sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
