# SonarQube - MenUnderFire Backend
sonar.projectKey=MenUnderFire-backend
sonar.projectName=Men Under Fire - Backend
sonar.projectVersion=1.0

sonar.host.url=http://172.16.255.10:9002

sonar.sources=cmd,internal
sonar.tests=.

sonar.test.inclusions=**/*_test.go
sonar.exclusions=\
  **/vendor/**,\
  **/*.exe,\
  **/logs/**,\
  **/*_test.go

sonar.go.coverage.reportPaths=coverage.out

sonar.sourceEncoding=UTF-8
